# Generated by Django 2.2.8 on 2019-12-21 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailvideos', '0005_video_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
    ]
