# Generated by Django 2.2.8 on 2019-12-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailvideos', '0002_auto_20191221_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='scope',
            field=models.CharField(blank=True, choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=30, verbose_name='Scope'),
        ),
    ]
